spring.application.name=healthcare project

spring.profiles.active=development
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare
spring.datasource.username=healthcare_user
spring.datasource.password=passworduntukHealthcare1234)(*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# swagger properties

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=swagger-ui.html

# flyway conf

spring.flyway.enabled=false

# jwt configuration
app.jwtSecret=f91056f6660d2855549779b2b305bcd9a085743d8af821bdb9fb32b5ec8033d6
app.jwtExpirationTime=3d

# xendit
xendit.api-key=xnd_development_3YlKhg1QwU5Rz5Xu85YGVC7fSvEer52NpQxldHIDiFXNLztn8OPZO1SiHthLP0c4
xendit.public-key=xnd_public_development_OUAYjcNzoztLaseh8SFJPtnrs4p4kNzFjUFiE8qox5mry5Gf0dV9Dk1Ze4aIWs

# videosdk
videosdk.base-url=https://api.videosdk.live/v2
videosdk.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiIyYmRiNzc1OC1jNDhmLTRmMDMtOGFhYy1lZWFhZjJlOTJjZTYiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTcyOTY5ODg3OSwiZXhwIjoxNzMwMzAzNjc5fQ.Wb9kHmXou7FQ_-vSFFPPM_plrbJ0V5oFky3pmuGvsdc