spring.application.name=healthcare project

spring.profiles.active=development
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare
spring.datasource.username=healthcare_user
spring.datasource.password=passworduntukHealthcare1234)(*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# swagger properties

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=swagger-ui.html

# flyway conf

spring.flyway.enabled=false

# jwt configuration
app.jwtSecret=f91056f6660d2855549779b2b305bcd9a085743d8af821bdb9fb32b5ec8033d6
app.jwtExpirationTime=3d

# xendit
xendit.api-key=
xendit.public-key=

# videosdk
videosdk.base-url=
videosdk.api-key=

# sendgrid
sendgrid.api-key=
sendgrid.from-email=elanqist@gmail.com
email.template.payment-successful=
email.template.meeting-created=

# Mengaktifkan metrik untuk sistem operasi, file, dan prosesor
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true
# Expose all Actuator endpoints
management.endpoints.web.exposure.include=*
# Enable the Prometheus endpoint
management.endpoint.prometheus.enabled=true
# Enable detailed health information
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
